// <auto-generated />
using System;
using ControleVendas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleVendas.Migrations
{
    [DbContext(typeof(ControleVendasContext))]
    [Migration("20201207031223_ClienteTrabalho")]
    partial class ClienteTrabalho
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ControleVendas.Models.ClienteModel", b =>
                {
                    b.Property<long?>("ClienteModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteModelId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ControleVendas.Models.PedidoModel", b =>
                {
                    b.Property<long?>("PedidoModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("ClienteModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ProdutoModelId")
                        .HasColumnType("bigint");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("PedidoModelId");

                    b.HasIndex("ClienteModelId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ControleVendas.Models.ProdutoModel", b =>
                {
                    b.Property<long?>("ProdutoModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoUnit")
                        .HasColumnType("float");

                    b.HasKey("ProdutoModelId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("PedidoModelProdutoModel", b =>
                {
                    b.Property<long>("PedidosPedidoModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutosProdutoModelId")
                        .HasColumnType("bigint");

                    b.HasKey("PedidosPedidoModelId", "ProdutosProdutoModelId");

                    b.HasIndex("ProdutosProdutoModelId");

                    b.ToTable("PedidoModelProdutoModel");
                });

            modelBuilder.Entity("ControleVendas.Models.PedidoModel", b =>
                {
                    b.HasOne("ControleVendas.Models.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteModelId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PedidoModelProdutoModel", b =>
                {
                    b.HasOne("ControleVendas.Models.PedidoModel", null)
                        .WithMany()
                        .HasForeignKey("PedidosPedidoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleVendas.Models.ProdutoModel", null)
                        .WithMany()
                        .HasForeignKey("ProdutosProdutoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
